// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: flag.proto

package flag

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FlagRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FirstCondition  *string                `protobuf:"bytes,2,req,name=first_condition,json=firstCondition,def=TraLaLeRo TraLaLa" json:"first_condition,omitempty"`
	SecondCondition []byte                 `protobuf:"bytes,3,req,name=second_condition,json=secondCondition,def=cafebabe" json:"second_condition,omitempty"`
	LastCondition   *uint64                `protobuf:"fixed64,1,req,name=last_condition,json=lastCondition,def=3141592654" json:"last_condition,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

// Default values for FlagRequest fields.
const (
	Default_FlagRequest_FirstCondition = string("TraLaLeRo TraLaLa")
	Default_FlagRequest_LastCondition  = uint64(3141592654)
)

// Default values for FlagRequest fields.
var (
	Default_FlagRequest_SecondCondition = []byte("cafebabe")
)

func (x *FlagRequest) Reset() {
	*x = FlagRequest{}
	mi := &file_flag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlagRequest) ProtoMessage() {}

func (x *FlagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlagRequest.ProtoReflect.Descriptor instead.
func (*FlagRequest) Descriptor() ([]byte, []int) {
	return file_flag_proto_rawDescGZIP(), []int{0}
}

func (x *FlagRequest) GetFirstCondition() string {
	if x != nil && x.FirstCondition != nil {
		return *x.FirstCondition
	}
	return Default_FlagRequest_FirstCondition
}

func (x *FlagRequest) GetSecondCondition() []byte {
	if x != nil && x.SecondCondition != nil {
		return x.SecondCondition
	}
	return append([]byte(nil), Default_FlagRequest_SecondCondition...)
}

func (x *FlagRequest) GetLastCondition() uint64 {
	if x != nil && x.LastCondition != nil {
		return *x.LastCondition
	}
	return Default_FlagRequest_LastCondition
}

type FlagReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Flag          *string                `protobuf:"bytes,1,req,name=flag" json:"flag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlagReply) Reset() {
	*x = FlagReply{}
	mi := &file_flag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlagReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlagReply) ProtoMessage() {}

func (x *FlagReply) ProtoReflect() protoreflect.Message {
	mi := &file_flag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlagReply.ProtoReflect.Descriptor instead.
func (*FlagReply) Descriptor() ([]byte, []int) {
	return file_flag_proto_rawDescGZIP(), []int{1}
}

func (x *FlagReply) GetFlag() string {
	if x != nil && x.Flag != nil {
		return *x.Flag
	}
	return ""
}

type HelloReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *string                `protobuf:"bytes,1,req,name=message" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloReply) Reset() {
	*x = HelloReply{}
	mi := &file_flag_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloReply) ProtoMessage() {}

func (x *HelloReply) ProtoReflect() protoreflect.Message {
	mi := &file_flag_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloReply.ProtoReflect.Descriptor instead.
func (*HelloReply) Descriptor() ([]byte, []int) {
	return file_flag_proto_rawDescGZIP(), []int{2}
}

func (x *HelloReply) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

var File_flag_proto protoreflect.FileDescriptor

const file_flag_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"flag.proto\x12\x04flag\x1a\x1bgoogle/protobuf/empty.proto\"\xb1\x01\n" +
	"\vFlagRequest\x12:\n" +
	"\x0ffirst_condition\x18\x02 \x02(\t:\x11TraLaLeRo TraLaLaR\x0efirstCondition\x123\n" +
	"\x10second_condition\x18\x03 \x02(\f:\bcafebabeR\x0fsecondCondition\x121\n" +
	"\x0elast_condition\x18\x01 \x02(\x06:\n" +
	"3141592654R\rlastCondition\"\x1f\n" +
	"\tFlagReply\x12\x12\n" +
	"\x04flag\x18\x01 \x02(\tR\x04flag\"&\n" +
	"\n" +
	"HelloReply\x12\x18\n" +
	"\amessage\x18\x01 \x02(\tR\amessage2l\n" +
	"\x04Flag\x12/\n" +
	"\aGetFlag\x12\x11.flag.FlagRequest\x1a\x0f.flag.FlagReply\"\x00\x123\n" +
	"\x05Hello\x12\x16.google.protobuf.Empty\x1a\x10.flag.HelloReply\"\x00B Z\x1ectf.nusgreyhats.org/sgrpc/flag"

var (
	file_flag_proto_rawDescOnce sync.Once
	file_flag_proto_rawDescData []byte
)

func file_flag_proto_rawDescGZIP() []byte {
	file_flag_proto_rawDescOnce.Do(func() {
		file_flag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_flag_proto_rawDesc), len(file_flag_proto_rawDesc)))
	})
	return file_flag_proto_rawDescData
}

var file_flag_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_flag_proto_goTypes = []any{
	(*FlagRequest)(nil),   // 0: flag.FlagRequest
	(*FlagReply)(nil),     // 1: flag.FlagReply
	(*HelloReply)(nil),    // 2: flag.HelloReply
	(*emptypb.Empty)(nil), // 3: google.protobuf.Empty
}
var file_flag_proto_depIdxs = []int32{
	0, // 0: flag.Flag.GetFlag:input_type -> flag.FlagRequest
	3, // 1: flag.Flag.Hello:input_type -> google.protobuf.Empty
	1, // 2: flag.Flag.GetFlag:output_type -> flag.FlagReply
	2, // 3: flag.Flag.Hello:output_type -> flag.HelloReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_flag_proto_init() }
func file_flag_proto_init() {
	if File_flag_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_flag_proto_rawDesc), len(file_flag_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_flag_proto_goTypes,
		DependencyIndexes: file_flag_proto_depIdxs,
		MessageInfos:      file_flag_proto_msgTypes,
	}.Build()
	File_flag_proto = out.File
	file_flag_proto_goTypes = nil
	file_flag_proto_depIdxs = nil
}
