FROM grey.ctf/evm-infra

COPY ./contracts /tmp/contracts
COPY ./foundry.toml /tmp/foundry.toml

ENV FLAG "grey{rational_math_fixes_rounding_67c1b078}"
ENV PUBLIC_IP "challs.nusgreyhats.org"
ENV HTTP_PORT 33504
