FROM grey.ctf/evm-infra

COPY ./contracts /tmp/contracts
COPY ./foundry.toml /tmp/foundry.toml

ENV PUBLIC_IP "challs.nusgreyhats.org"
ENV FLAG "grey{cant_delete_mapping_c60126ce}"
ENV HTTP_PORT 34224
