# source filesystem
FROM ubuntu:22.04 AS app

# this is the actual container that runs
FROM pwn.red/jail
# copy ubuntu file system into our redpwn jail
COPY --from=app / /srv
# copy local file into docker
COPY ./quiz /srv/app/run
RUN chmod 555  /srv/app/run
# copy flag into docker if needed
COPY ./flag.txt /srv/app/flag.txt
