services:
  challenge:
    container_name: web-oops-app
    build:
      context: service/app
      dockerfile: Dockerfile
    ports:
      - "33001:5000"
  admin:
    container_name: web-oops-admin
    build:
      context: service/admin
      dockerfile: Dockerfile
    restart: always
    environment:
      - FLAG=grey{oops_wrong_variable}
