// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: flag.proto

package flag

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Flag_GetFlag_FullMethodName = "/flag.Flag/GetFlag"
	Flag_Hello_FullMethodName   = "/flag.Flag/Hello"
)

// FlagClient is the client API for Flag service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FlagClient interface {
	GetFlag(ctx context.Context, in *FlagRequest, opts ...grpc.CallOption) (*FlagReply, error)
	Hello(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HelloReply, error)
}

type flagClient struct {
	cc grpc.ClientConnInterface
}

func NewFlagClient(cc grpc.ClientConnInterface) FlagClient {
	return &flagClient{cc}
}

func (c *flagClient) GetFlag(ctx context.Context, in *FlagRequest, opts ...grpc.CallOption) (*FlagReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FlagReply)
	err := c.cc.Invoke(ctx, Flag_GetFlag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flagClient) Hello(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HelloReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, Flag_Hello_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FlagServer is the server API for Flag service.
// All implementations must embed UnimplementedFlagServer
// for forward compatibility.
type FlagServer interface {
	GetFlag(context.Context, *FlagRequest) (*FlagReply, error)
	Hello(context.Context, *emptypb.Empty) (*HelloReply, error)
	mustEmbedUnimplementedFlagServer()
}

// UnimplementedFlagServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFlagServer struct{}

func (UnimplementedFlagServer) GetFlag(context.Context, *FlagRequest) (*FlagReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFlag not implemented")
}
func (UnimplementedFlagServer) Hello(context.Context, *emptypb.Empty) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hello not implemented")
}
func (UnimplementedFlagServer) mustEmbedUnimplementedFlagServer() {}
func (UnimplementedFlagServer) testEmbeddedByValue()              {}

// UnsafeFlagServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FlagServer will
// result in compilation errors.
type UnsafeFlagServer interface {
	mustEmbedUnimplementedFlagServer()
}

func RegisterFlagServer(s grpc.ServiceRegistrar, srv FlagServer) {
	// If the following call pancis, it indicates UnimplementedFlagServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Flag_ServiceDesc, srv)
}

func _Flag_GetFlag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlagServer).GetFlag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Flag_GetFlag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlagServer).GetFlag(ctx, req.(*FlagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Flag_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlagServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Flag_Hello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlagServer).Hello(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Flag_ServiceDesc is the grpc.ServiceDesc for Flag service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Flag_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "flag.Flag",
	HandlerType: (*FlagServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFlag",
			Handler:    _Flag_GetFlag_Handler,
		},
		{
			MethodName: "Hello",
			Handler:    _Flag_Hello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "flag.proto",
}
